server:
  port: 8080

spring:
  application:
    name: api-gateway


  security:
    jwt:
      secret: ${JWT_SECRET}

  cloud:
    gateway:
      routes:
        # USER SERVICE ROUTES (Port 8081) 
        - id: user-auth-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
         

        - id: user-profile-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

          #  EXPENSE SERVICE ROUTES (Port 8083) 
        - id: group-expense-route
          uri: http://localhost:8083
          order: 1
          predicates:
            - Path=/api/v1/groups/{groupId}/expenses
          filters:
            - AuthenticationFilter

        - id: expense-route
          uri: http://localhost:8083
          order: 1
          predicates:
            - Path=/api/v1/expenses/**
          filters:
            - AuthenticationFilter

        # --- GROUP SERVICE ROUTES (Port 8082) ---
        - id: group-route
          uri: http://localhost:8082
          order: 2
          predicates:
            - Path=/api/v1/groups/**
          filters:
            - AuthenticationFilter
        # --- BALANCE SERVICE ROUTES (Port 8084) ---
        # - id: balance-route
        #   uri: http://localhost:8084
        #   filters:
        #     -AuthenticationFilter