server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    jwt:
      secret: ${JWT_SECRET}

  cloud:
    gateway:
      routes:

        # USER SERVICE
        - id: user-auth-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: user-profile-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**   # Verify your controller uses /users
          filters:
            - AuthenticationFilter

        # EXPENSE SERVICE
        - id: group-expense-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/groups/{groupId}/expenses
          filters:
            - AuthenticationFilter

        - id: expense-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/expenses/**
          filters:
            - AuthenticationFilter

        # GROUP SERVICE
        - id: group-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/groups/**
          filters:
            - AuthenticationFilter

        # BALANCE SERVICE
        - id: balance-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/balances/**
          filters:
            - AuthenticationFilter